steps:
  # ===============================
  #  BACKEND BUILD
  # ===============================
  - id: build-backend
    name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:$BUILD_ID",
        "-f",
        "langgraph_app/Dockerfile",
        "."
      ]

  # ===============================
  #  BACKEND DEPLOY
  # ===============================
  - id: deploy-backend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "writerzroom-backend-api",
        "--image=us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:$BUILD_ID",
        "--region=us-central1",
        "--vpc-connector=writerzroom-connector",
        "--vpc-egress=all-traffic",
        "--no-allow-unauthenticated"
      ]

  # ===============================
  #  FRONTEND BUILD
  # ===============================
  - id: build-frontend
    name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:$BUILD_ID",
        "-t",
        "us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:latest",
        "-f",
        "frontend/Dockerfile",
        "."
      ]

  # ===============================
  #  FRONTEND DEPLOY
  # ===============================
  - id: deploy-frontend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "writerzroom-frontend-web",
        "--image=us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:$BUILD_ID",
        "--region=us-central1",
        "--allow-unauthenticated"
      ]

# ===============================
#  IMAGES TO PUSH
# ===============================
images:
  - us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:$BUILD_ID
  - us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:$BUILD_ID
