timeout: '1800s'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 100

steps:
  # === Build backend ===
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build','-t','us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:$COMMIT_SHA','-t','us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:latest','-f','langgraph_app/Dockerfile','.']
    id: build-backend

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:$COMMIT_SHA']
    id: push-backend-sha

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:latest']
    id: push-backend-latest

  # === Deploy backend ===
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      ['run','deploy','writerzroom-backend-api',
       '--image=us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:$COMMIT_SHA',
       '--region=us-central1',
       '--platform=managed',
       '--allow-unauthenticated',
       '--port=8000',
       '--vpc-connector=writerzroom-connector',
       '--vpc-egress=all-traffic',
       '--cpu=2',
       '--memory=8Gi',
       '--timeout=900s',
       '--concurrency=12',
       '--min-instances=1',
       '--max-instances=50',
       '--set-env-vars=PORT=8000,APP_ENV=production,LOG_LEVEL=INFO',
       '--set-secrets=OPENAI_API_KEY=openai-key:latest,ANTHROPIC_API_KEY=anthropic-key:latest,DATABASE_URL=database-url:latest,REDIS_URL=redis-url:latest,TAVILY_API_KEY=tavily-key:latest,FASTAPI_API_KEY=fastapi-key:latest,SECRET_KEY=backend-secret-key:latest']    
    id: deploy-backend

  # === Build frontend ===
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build','-t','us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:$COMMIT_SHA','-t','us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:latest','-f','frontend/Dockerfile','./frontend']
    id: build-frontend

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:$COMMIT_SHA']
    id: push-frontend-sha

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:latest']
    id: push-frontend-latest

  # === Deploy frontend ===
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      ['run','deploy','writerzroom-frontend-web',
       '--image=us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:$COMMIT_SHA',
       '--region=us-central1',
       '--platform=managed',
       '--allow-unauthenticated',
       '--port=3000',
       '--cpu=1',
       '--memory=1Gi',
       '--set-env-vars=PORT=3000,NODE_ENV=production']
    id: deploy-frontend