timeout: '1800s'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 100

steps:
  # === Build backend (NO CACHE) ===
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --no-cache \
          -t us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:$BUILD_ID \
          -t us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:latest \
          -f langgraph_app/Dockerfile \
          .

  # Push backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:latest'

  # === Deploy backend ===
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud run deploy writerzroom-backend-api \
          --image=us-central1-docker.pkg.dev/agentic-writer/writerzroom/backend:$BUILD_ID \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --vpc-connector=writerzroom-connector \
          --vpc-egress=all-traffic \
          --cpu=2 \
          --memory=8Gi \
          --timeout=900s \
          --concurrency=12 \
          --min-instances=1 \
          --max-instances=50 \
          --service-account=writerzroom-backend@agentic-writer.iam.gserviceaccount.com \
          --set-env-vars=APP_ENV=production,LOG_LEVEL=INFO \
          --set-secrets=OPENAI_API_KEY=openai-key:latest,ANTHROPIC_API_KEY=anthropic-key:latest,DATABASE_URL=database-url:latest,TAVILY_API_KEY=tavily-key:latest,FASTAPI_API_KEY=fastapi-key:latest,SECRET_KEY=backend-secret-key:latest

  # === Build frontend (NO CACHE) ===
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --no-cache \
          -t us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:$BUILD_ID \
          -t us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:latest \
          -f frontend/Dockerfile \
          ./frontend

  # Push frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:latest'

  # === Deploy frontend ===
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy writerzroom-frontend-web \
          --image=us-central1-docker.pkg.dev/agentic-writer/writerzroom/frontend:$BUILD_ID \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=3000 \
          --cpu=1 \
          --memory=1Gi \
          --set-env-vars=NODE_ENV=production
