"use client";

import React, { useState, useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Form } from "@/components/ui/form";
import { SubmitHandler } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { useEnhancedGeneration } from "@/hooks/useEnhancedGeneration";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { 
  Check, 
  Copy, 
  Download, 
  Save,
  Palette, 
  Eye, 
  FileText, 
  Loader2, 
  Sparkles, 
  Zap, 
  AlertCircle 
} from "lucide-react";

import TemplateSelector from "@/components/TemplateSelector";
import DynamicParameters from "@/components/DynamicParameters";
import { useQueryClient } from "@tanstack/react-query";
import GeneratingDialog from "@/components/GeneratingDialog";
import { useTemplates } from "@/hooks/useTemplates";
import { Template } from "@/types/template";
import StyleProfilesSelector from "@/components/StyleProfilesSelector";
import { useStyleProfiles } from "@/hooks/useStyleProfiles";
import { 
  adaptTemplateCollection} from "@/utils/typeAdapters";
import { z } from "zod";

// Schema Definition
const generateContentSchema = z.object({
  templateId: z.string().min(1),
  styleProfileId: z.string().min(1),
  dynamic_parameters: z.record(z.union([z.string(), z.number(), z.boolean()])),
  platform: z.string(),
});

type GenerateContentFormValues = z.infer<typeof generateContentSchema>;

interface ExtendedStyleProfile {
  id: string;
  name: string;
  description?: string;
  category?: string;
  tone?: string;
  voice?: string;
  structure?: string;
  system_prompt?: string;
  settings?: Record<string, unknown>;
  filename?: string;
}

// Environment configuration
const USE_BACKEND_API = process.env.NEXT_PUBLIC_USE_BACKEND_API === 'true';

// Enhanced Generation Preview Component
const EnhancedGenerationPreview = ({ 
  isGenerating, 
  generatedContent, 
  onCancel, 
  onSave, 
  templateName, 
  styleProfile 
}: {
  isGenerating: boolean;
  generatedContent?: string;
  onCancel: () => void;
  onSave: () => void;
  templateName?: string;
  styleProfile?: string;
}) => {
  const [isPreview, setIsPreview] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);

  const handleCopy = async () => {
    if (!generatedContent) return;
    
    try {
      await navigator.clipboard.writeText(generatedContent);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleExport = (format: 'markdown' | 'html' | 'pdf') => {
    if (!generatedContent) return;

    let exportContent = generatedContent;
    let fileName = `generated-content-${new Date().toISOString().split('T')[0]}.${format}`;
    let mimeType = 'text/plain';

    switch (format) {
      case 'html':
        exportContent = `<!DOCTYPE html>
<html>
<head>
  <title>Generated Content</title>
  <meta charset="UTF-8">
  <style>
    body { 
      font-family: Georgia, 'Times New Roman', serif;
      max-width: 800px; 
      margin: 0 auto; 
      padding: 3rem 2rem; 
      line-height: 1.8; 
      color: #2d3748;
      background: #ffffff;
    }
    h1 { 
      color: #1a202c; 
      font-size: 2.5rem; 
      margin-bottom: 1.5rem; 
      border-bottom: 3px solid #667eea;
      padding-bottom: 0.5rem;
    }
    h2 { 
      color: #2d3748; 
      font-size: 1.875rem; 
      margin-top: 2.5rem; 
      margin-bottom: 1rem;
    }
    h3 { 
      color: #4a5568; 
      font-size: 1.5rem; 
      margin-top: 2rem; 
      margin-bottom: 0.75rem;
    }
    p { 
      margin-bottom: 1.25rem; 
      text-align: justify;
      text-indent: 1.5rem;
    }
    strong { color: #1a202c; }
    em { color: #4a5568; }
    blockquote {
      border-left: 4px solid #667eea;
      padding-left: 1.5rem;
      margin: 1.5rem 0;
      font-style: italic;
      color: #4a5568;
    }
    .metadata {
      background: #f7fafc;
      padding: 1.5rem;
      border-radius: 8px;
      margin: 2rem 0;
      border: 1px solid #e2e8f0;
    }
    .export-note {
      font-size: 0.875rem;
      color: #718096;
      text-align: center;
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid #e2e8f0;
    }
  </style>
</head>
<body>
  <div class="metadata">
    <strong>Generated with:</strong> ${templateName || 'Unknown Template'}<br>
    <strong>Style:</strong> ${styleProfile || 'Default'}<br>
    <strong>Generated:</strong> ${new Date().toLocaleString()}
  </div>
  
  ${convertMarkdownToHTML(generatedContent)}
  
  <div class="export-note">
    Generated by AgentWrite Pro • ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`;
        mimeType = 'text/html';
        break;
        
      case 'pdf':
        // For PDF, create print-optimized HTML
        exportContent = createPrintOptimizedHTML(generatedContent, templateName, styleProfile);
        fileName = fileName.replace('.pdf', '.html');
        mimeType = 'text/html';
        break;
        
      default:
        // Markdown format
        exportContent = `# Generated Content

**Template:** ${templateName || 'Unknown'}  
**Style:** ${styleProfile || 'Default'}  
**Generated:** ${new Date().toLocaleString()}

---

${generatedContent}

---
*Generated by AgentWrite Pro*`;
    }

    const blob = new Blob([exportContent], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (isGenerating) {
    return (
      <Card className="bg-white/10 backdrop-blur-sm border-white/20">
        <CardContent className="p-8 text-center">
          <Loader2 className="h-12 w-12 animate-spin text-purple-400 mx-auto mb-4" />
          <h3 className="text-xl font-semibold text-white mb-2">Generating Content...</h3>
          <p className="text-gray-300">Please wait while our AI creates your content</p>
          <Button 
            variant="outline" 
            onClick={onCancel}
            className="mt-4 border-white/20 text-white hover:bg-white/10"
          >
            Cancel
          </Button>
        </CardContent>
      </Card>
    );
  }

  if (!generatedContent) {
    return null;
  }

  return (
    <Card className="bg-white/10 backdrop-blur-sm border-white/20">
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-white flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Generated Content
          </CardTitle>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setIsPreview(!isPreview)}
              className="border-white/20 text-white hover:bg-white/10"
            >
              <Eye className="h-4 w-4 mr-1" />
              {isPreview ? 'Raw' : 'Preview'}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className="border-white/20 text-white hover:bg-white/10"
            >
              {copySuccess ? (
                <Check className="h-4 w-4 mr-1" />
              ) : (
                <Copy className="h-4 w-4 mr-1" />
              )}
              {copySuccess ? 'Copied!' : 'Copy'}
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {/* Content Stats */}
        <div className="flex items-center gap-4 mb-4 text-sm text-gray-300">
          <span>{generatedContent.split(/\s+/).length} words</span>
          <span>{generatedContent.length} characters</span>
          <span>{Math.ceil(generatedContent.split(/\s+/).length / 200)} min read</span>
        </div>

        {/* Content Display */}
        <div className="mb-6">
          {isPreview ? (
            <div className="bg-white rounded-lg p-6 shadow-inner">
              <div 
                className="prose prose-lg max-w-none text-gray-800"
                style={{
                  fontFamily: 'Georgia, "Times New Roman", serif',
                  lineHeight: '1.8',
                  fontSize: '1.1rem'
                }}
                dangerouslySetInnerHTML={{ 
                  __html: convertMarkdownToHTML(generatedContent) 
                }}
              />
            </div>
          ) : (
            <div className="bg-gray-900 rounded-lg p-4 border border-gray-700">
              <pre className="text-gray-200 whitespace-pre-wrap font-mono text-sm overflow-x-auto">
                {generatedContent}
              </pre>
            </div>
          )}
        </div>

        {/* Export Options */}
        <div className="flex flex-wrap items-center justify-between gap-4 pt-4 border-t border-white/20">
          <div className="flex flex-wrap gap-2">
            <Button
              onClick={() => handleExport('markdown')}
              variant="outline"
              size="sm"
              className="border-white/20 text-white hover:bg-white/10"
            >
              <Download className="h-4 w-4 mr-1" />
              Markdown
            </Button>
            <Button
              onClick={() => handleExport('html')}
              variant="outline"
              size="sm"
              className="border-white/20 text-white hover:bg-white/10"
            >
              <Download className="h-4 w-4 mr-1" />
              HTML
            </Button>
            <Button
              onClick={() => handleExport('pdf')}
              variant="outline"
              size="sm"
              className="border-white/20 text-white hover:bg-white/10"
            >
              <Download className="h-4 w-4 mr-1" />
              PDF Ready
            </Button>
          </div>
          
          <Button
            onClick={onSave}
            className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600"
          >
            <Save className="h-4 w-4 mr-2" />
            Save Content
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};

// Helper function to convert markdown-like content to HTML
function convertMarkdownToHTML(content: string): string {
  return content
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^#### (.+)$/gm, '<h4>$1</h4>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>)/g, '<ul>$1</ul>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(?!<[uo]l>|<h[1-6]>)(.+)$/gm, '<p>$1</p>')
    .replace(/<\/p><p><ul>/g, '</p><ul>')
    .replace(/<\/ul><p>/g, '</ul><p>');
}

// Helper function to create print-optimized HTML for PDF
function createPrintOptimizedHTML(content: string, templateName?: string, styleProfile?: string): string {
  return `<!DOCTYPE html>
<html>
<head>
  <title>Generated Content - Print Version</title>
  <meta charset="UTF-8">
  <style>
    @page { 
      margin: 1in; 
      size: A4;
    }
    body { 
      font-family: 'Times New Roman', serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
      background: #fff;
    }
    h1 { 
      font-size: 18pt; 
      margin-bottom: 12pt; 
      page-break-after: avoid;
    }
    h2 { 
      font-size: 16pt; 
      margin-top: 18pt; 
      margin-bottom: 10pt; 
      page-break-after: avoid;
    }
    h3 { 
      font-size: 14pt; 
      margin-top: 14pt; 
      margin-bottom: 8pt; 
      page-break-after: avoid;
    }
    p { 
      margin-bottom: 8pt; 
      text-align: justify;
    }
    .header {
      border-bottom: 1pt solid #000;
      padding-bottom: 8pt;
      margin-bottom: 16pt;
    }
    .footer {
      margin-top: 24pt;
      padding-top: 8pt;
      border-top: 1pt solid #000;
      font-size: 10pt;
      text-align: center;
    }
    @media print {
      body { margin: 0; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <strong>Template:</strong> ${templateName || 'Unknown'}<br>
    <strong>Style:</strong> ${styleProfile || 'Default'}<br>
    <strong>Generated:</strong> ${new Date().toLocaleString()}
  </div>
  
  ${convertMarkdownToHTML(content)}
  
  <div class="footer">
    Generated by AgentWrite Pro • ${new Date().toLocaleDateString()}
  </div>
  
  <div class="no-print" style="position: fixed; top: 20px; right: 20px;">
    <button onclick="window.print()" style="background: #2563eb; color: white; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;">
      Print to PDF
    </button>
  </div>
</body>
</html>`;
}

// Main Component
export default function GeneratePage() {
  const [isGeneratingDialogOpen, setIsGeneratingDialogOpen] = useState(false);
  
  const { data: styleProfiles, isLoading: profilesLoading, isError: profilesError } = useStyleProfiles();
  const { data: templates, isLoading: templatesLoading, isError: templatesError, error: templatesErrorDetails } = useTemplates();

  const {
    isGenerating,
    result,
    error,
    startGeneration,
    cancelGeneration,
    resetGeneration,
  } = useEnhancedGeneration();

  const form = useForm({
    resolver: zodResolver(generateContentSchema),
    defaultValues: {
      templateId: "",
      styleProfileId: "",
      dynamic_parameters: {},
      platform: "web",
    },
    mode: "onChange",
  });

  const watchedTemplateId = form.watch("templateId");
  const watchedStyleProfileId = form.watch("styleProfileId");

  // Safe template and style profile finding with null checking
  // Adapt templates to ensure they conform to the Template type (with 'name' property)
  const adaptedTemplates: Template[] = adaptTemplateCollection(templates || []).map((t) => {
    // If t already has a name, use it; otherwise, fallback to title or "Untitled Template"
    const name =
      typeof t === "object" && t !== null && "name" in t && typeof (t as { name?: unknown }).name === "string"
        ? (t as { name: string }).name
        : typeof t === "object" && t !== null && "title" in t && typeof (t as { title?: unknown }).title === "string"
        ? (t as { title: string }).title
        : "Untitled Template";
    return {
      ...t,
      name,
    } as Template;
  });
  const selectedTemplate: Template | null = adaptedTemplates && Array.isArray(adaptedTemplates) && watchedTemplateId
    ? adaptedTemplates.find((t: Template) => t && t.id === watchedTemplateId) || null
    : null;
  console.log('🔍 Debug Template Selection:', {
    watchedTemplateId,
    templatesCount: templates?.length,
    selectedTemplate,
    selectedTemplateParams: selectedTemplate?.parameters,
    adaptedTemplates: adaptedTemplates?.slice(0, 2), // Show first 2
  });
    
  const selectedStyleProfile: ExtendedStyleProfile | null = styleProfiles && Array.isArray(styleProfiles) && watchedStyleProfileId
    ? styleProfiles.find((sp: ExtendedStyleProfile) => sp && sp.id === watchedStyleProfileId) || null
    : null;

  const queryClient = useQueryClient();

  // Force fresh data on page load to fix caching issues
  useEffect(() => {
    queryClient.invalidateQueries({ queryKey: ['templates'] });
    queryClient.invalidateQueries({ queryKey: ['style-profiles'] });
  }, [queryClient]);

  // Handle URL parameters for template pre-selection
  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const templateParam = urlParams.get('template');
    
    if (templateParam && templates?.find(t => t.id === templateParam)) {
      form.setValue('templateId', templateParam);
      console.log('Template pre-selected from URL:', templateParam);
    }
  }, [templates, form]);

  // Update selected template parameters
  useEffect(() => {
    if (selectedTemplate?.parameters && typeof selectedTemplate.parameters === 'object') {
      try {
        const newDefaults: Record<string, string | number | boolean> = {};
        Object.entries(selectedTemplate.parameters).forEach(([paramName, param]) => {
          if (!param || typeof param !== 'object' || !paramName) {
            console.warn('Invalid parameter:', param);
            return;
          }
          
          if (param.default !== undefined) {
            newDefaults[paramName] = param.default;
          } else {
            switch (param.type) {
              case "text":
              case "textarea":
              case "select":
              case "string":
                newDefaults[paramName] = "";
                break;
              case "number":
                newDefaults[paramName] = 0;
                break;
              case "checkbox":
                newDefaults[paramName] = false;
                break;
              default:
                newDefaults[paramName] = "";
            }
          }
        });
        form.resetField("dynamic_parameters", { defaultValue: newDefaults });
      } catch (error) {
        console.error('Error processing template parameters:', error);
      }
    }
  }, [watchedTemplateId, selectedTemplate, form]);

  useEffect(() => {
    setIsGeneratingDialogOpen(isGenerating);
  }, [isGenerating]);

  if (templatesLoading || profilesLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
          <p className="mt-4 text-gray-600">Loading templates and style profiles...</p>
        </div>
      </div>
    );
  }

  if (templatesError || profilesError) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <Card className="bg-red-50 dark:bg-red-950 border-red-200 dark:border-red-800 max-w-md">
            <CardContent className="pt-6">
              <div className="flex items-center gap-3 text-red-700 dark:text-red-300">
                <AlertCircle className="h-5 w-5" />
                <div>
                  <h3 className="font-medium">Error Loading Data</h3>
                  <p className="text-sm mt-1">
                    {templatesError && "Failed to load templates. "}
                    {profilesError && "Failed to load style profiles."}
                  </p>
                  {templatesErrorDetails?.message && (
                    <p className="text-xs text-gray-500 mt-2">
                      {templatesErrorDetails.message}
                    </p>
                  )}
                </div>
              </div>
              <Button 
                variant="outline" 
                className="mt-4 w-full" 
                onClick={() => window.location.reload()}
              >
                Retry
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  if (!templates || !Array.isArray(templates) || templates.length === 0) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <Card className="bg-yellow-50 dark:bg-yellow-950 border-yellow-200 dark:border-yellow-800 max-w-md">
            <CardContent className="pt-6">
              <div className="flex items-center gap-3 text-yellow-700 dark:text-yellow-300">
                <AlertCircle className="h-5 w-5" />
                <div>
                  <h3 className="font-medium">No Templates Available</h3>
                  <p className="text-sm mt-1">
                    No templates found. Please check your backend connection.
                  </p>
                  <p className="text-xs text-gray-500 mt-2">
                    Templates: {templates?.length || 0} | Backend: {USE_BACKEND_API ? 'Enabled' : 'Disabled'}
                  </p>
                </div>
              </div>
              <Button 
                variant="outline" 
                className="mt-4 w-full" 
                onClick={() => window.location.reload()}
              >
                Refresh
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    );
}

const onSubmit: SubmitHandler<GenerateContentFormValues> = (values) => {
  console.log('🔍 Form submitted with values:', values);
  console.log('🔍 Dynamic parameters:', values.dynamic_parameters);
  
  const params = values.dynamic_parameters || {};
  
  console.log('🔍 Raw form parameters:', params);
  console.log('✅ Starting generation with all parameters...');
  
  startGeneration({
    template: values.templateId,
    style_profile: values.styleProfileId,
    dynamic_parameters: params, // Pass through all parameters as-is
    platform: values.platform,
    priority: 1,
    timeout_seconds: 300,
    generation_mode: 'standard',
  });
};

type GenerationResultMetadata = {
  saved_path?: string;
  [key: string]: unknown;
};

  const handleSaveContent = () => {
    if (result && 'metadata' in result && result.metadata) {
      const savedPath = (result.metadata as GenerationResultMetadata)?.saved_path;
      if (savedPath) {
        const slug = savedPath.split("/").pop()?.replace(/\.(json|md)$/, "");
        if (slug) {
          window.location.href = `/content/${slug}`;
          return;
        }
      }
    }
    
    window.location.href = '/content';
  };

  const canGenerate = 
    watchedTemplateId && 
    watchedStyleProfileId && 
    !isGenerating && 
    !templatesLoading && 
    !profilesLoading;

  return (
    <div className="max-w-6xl mx-auto space-y-8 text-gray-900 dark:text-white">
      {/* Enhanced Header */}
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
          Generate AI Content
        </h1>
        <p className="text-lg text-white max-w-2xl mx-auto">
          Create high-quality content using our advanced AI models. Select a template and style profile to get started.
        </p>
      </div>

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
          <div className="grid md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Sparkles className="h-5 w-5 text-purple-600" />
                  Content Template
                </CardTitle>
                <CardDescription>
                  Choose the type of content you want to generate.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <TemplateSelector
                  form={form}
                  templates={adaptTemplateCollection(templates || [])}
                  isLoadingTemplates={templatesLoading}
                />
                {selectedTemplate && (
                  <div className="mt-4">
                    <Badge variant="secondary" className="mb-2">
                      Selected Template
                    </Badge>
                    <p className="text-sm text-gray-600 dark:text-gray-300">
                      {selectedTemplate.description || selectedTemplate.name}
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                <Palette className="h-5 w-5 text-purple-600" />
                  Style Profile
                </CardTitle>
                <CardDescription>
                  Define the tone and style of your content.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <StyleProfilesSelector
                  value={watchedStyleProfileId}
                  onChange={(styleId) => form.setValue('styleProfileId', styleId)}
                  label=""
                  required={true}
                  showDescription={true}
                  disabled={profilesLoading}
                />
              </CardContent>
            </Card>
          </div>

         {selectedTemplate && selectedTemplate.parameters && typeof selectedTemplate.parameters === 'object' && Object.keys(selectedTemplate.parameters).length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>Template Parameters</CardTitle>
                <CardDescription>
                  Provide specific inputs for your selected template.
                </CardDescription>
              </CardHeader>
              <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <DynamicParameters 
                  parameters={Object.entries(selectedTemplate.parameters).map(([key, param]) => ({
                    name: key,
                    label: param.label,
                    type: param.type === "string" ? "text" : param.type as "text" | "textarea" | "select" | "number" | "checkbox",
                    options: param.options,
                    default: param.default,
                    required: param.required,
                    placeholder: param.placeholder,
                    description: param.description
                  }))} 
                />
              </CardContent>
            </Card>
          )}

          <Card className="border-2 border-dashed border-purple-200 dark:border-purple-800">
            <CardContent className="pt-6">
              <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-purple-100 dark:bg-purple-900 rounded-lg">
                    <Zap className="h-6 w-6 text-purple-600" />
                  </div>
                  <div>
                    <h3 className="font-semibold">Ready to Generate</h3>
                    <p className="text-sm text-gray-600 dark:text-gray-300">
                      {canGenerate 
                        ? "Click generate to create your content with AI"
                        : "Please select both template and style profile"
                      }
                    </p>
                  </div>
                </div>
                
                <div className="flex gap-2">
                  {(result || isGenerating) && (
                    <Button variant="outline" onClick={resetGeneration}>
                      New Generation
                    </Button>
                  )}
                  <Button
                    type="submit"
                    disabled={!canGenerate}
                    size="lg"
                    className="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700"
                  >
                    {isGenerating ? (
                      <>
                        <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Zap className="h-4 w-4 mr-2" />
                        Generate Content
                      </>
                    )}
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </form>
      </Form>

      {error && (
        <Card className="border-red-200 bg-red-50 dark:border-red-800 dark:bg-red-950">
          <CardContent className="pt-6">
            <div className="flex items-center gap-2 text-red-700 dark:text-red-300">
              <AlertCircle className="h-5 w-5" />
              <div>
                <span className="font-medium">Generation Failed:</span>
                <p className="text-sm mt-1">{error}</p>
                {!USE_BACKEND_API && (
                  <p className="text-xs text-red-600 dark:text-red-400 mt-2">
                    Tip: Enable backend API in environment variables for better reliability
                  </p>
                )}
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      <EnhancedGenerationPreview
        isGenerating={isGenerating}
        generatedContent={result?.content}
        onCancel={cancelGeneration}
        onSave={handleSaveContent}
        templateName={selectedTemplate?.name}
        styleProfile={selectedStyleProfile?.name}
      />

      <GeneratingDialog open={isGeneratingDialogOpen} />
    </div>
  );
}