"""create_generation_logs

Revision ID: 1746f6087666
Revises: 
Create Date: 2025-10-05 15:05:10.244033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1746f6087666'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=255), nullable=False),
    sa.Column('style_profile_id', sa.String(length=255), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('generation_time_seconds', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_logs_created_at'), 'generation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_generation_logs_style_profile_id'), 'generation_logs', ['style_profile_id'], unique=False)
    op.create_index(op.f('ix_generation_logs_template_id'), 'generation_logs', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_logs_template_id'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_style_profile_id'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_created_at'), table_name='generation_logs')
    op.drop_table('generation_logs')
    # ### end Alembic commands ###
